default_language_version:
    python: python3.10

repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black docker_compose_diagram tests
        language: python
        types: [python]

      - id: isort
        name: isort
        entry: poetry run isort docker_compose_diagram tests
        language: python
        types: [python]