[tool.poetry]
name = "docker-compose-diagram"
version = "0.2.0"
description = ""
authors = ["Skonik <s.konik.dev@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
PyYAML = "5.3.1"
diagrams = "^0.20.0"
click = "^8.0.3"
dockerfile-parse = "^1.2.0"
rich = "^12.2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
compose-diagram = 'docker_compose_diagram:process_cli'